### ISSUE TITLE
Failed to detect whether we are running on Google Compute Engine

### ISSUE THREAD

**Issue by AliredDevils** [googleapis/java-grafeas#78]
I try to make creating some notes test by java-grafeas of 0.24.0 version client api.But i get erros:
    
    com.google.auth.oauth2.ComputeEngineCredentials runningOnComputeEngine

    Information: Failed to detect whether we are running on Google Compute Engine.

    Exception in thread "main" java.lang.NullPointerException

	at grafeas.GrafeasData.createGrafeasNotes(GrafeasData.java:60)

	at grafeas.GrafeasData.main(GrafeasData.java:31)

#### Environment details

1. Create note API: `createNote(String parent, String noteId, Note note)`
2. Mac OS:
3. Java Version 1.8.0_144
4. 0.24.0 version:

#### Steps to reproduce

  1. run [grafeas server](https://github.com/grafeas/grafeas/tree/master/go/v1beta1) :  `go run main/main.go`
  2. run my client test program

#### Code example

```java
GrafeasClient apiClient = GrafeasClient.create();
NoteName name = NoteName.of(projectName, dockerScan.getVulnerability());
            Note noteBody = Note.newBuilder()
                    .setLongDescription(dockerScan.getDescription())
                    .setShortDescription(dockerScan.getVulnerability())
                    .setName(name.toString())
                    .setKind(NoteKind.VULNERABILITY)
                    .build();
            Note noteResponse = apiClient.createNote(projectName, dockerScan.getVulnerability(), noteBody);
            if (noteResponse != null) {
                logger.info(noteResponse.getLongDescription());
                logger.info(noteResponse.getName());
            } else {
                logger.error("note response null");
            }
```

  1.Shoud i create my own grafeas server for java-grafeas instead of v1beta1 ?
  2.Is there some limits for the Java-grafeas client api to use,such as environment, message engine,compute engine or others?
  3.If any test samples for the client api, for example:create or list notes?

Thanks!

**Comment by chingor13** [comment]
If you are using this client directly, you will need some kind of grafeas server set up. If you are trying to use Google's ContainerAnalysis service which implements the Grafeas API, you should look at `com.google.cloud:google-cloud-containeranalysis` which extends this client. See https://github.com/googleapis/java-containeranalysis

**Comment by chingor13** [comment]
Ah, it looks like you're using your own Grafeas server. In that case, you'll likely need to set the endpoint otherwise the client doesn't know where to connect to.

Try something like:
```java
GrafeasSettings settings = GrafeasSettings.newBuilder().setEndpoint(myEndpoint).build();
GrafeasClient client = GrafeasClient.create(settings);
```

**Comment by AliredDevils** [comment]
@chingor13   Thanks, i found the issue as i need to set my own endpoint.
By the way, can you give some suggestion about generating the java client jar package by `protoc` ?
BR

**Comment by chingor13** [comment]
Sorry, missed this response and additional question. If you are still having trouble with this, feel free to reopen (or open a separate question issue).
